name: Build Windows Executable

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Find main.py
        run: |
          find . -name main.py -type f -print
      - name: Build executable
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .
          spec: main.spec
          build: dist/windows
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: dist/windows
